# Generated by Django 5.1.2 on 2024-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertiser", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("format", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                ("impressions", models.BigIntegerField()),
            ],
        ),
    ]
